global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_app'
    static_configs:
      - targets: ['backend:3000']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'mongodb_exporter'
    static_configs:
      - targets: ['mongodb_exporter:9216']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

